apiVersion: v1
kind: Pod
spec:
  serviceAccount: jenkins
  containers:
  - name: shell
    image: alpine
    command:
    - cat
    tty: true
    imagePullPolicy: IfNotPresent
  - name: kaniko
    image: 839928622/kaniko-executor:debug
    command:
    - cat
    tty: true
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker/
    imagePullPolicy: IfNotPresent
  - name: kustomize
    image: nekottyo/kustomize-kubeval
    command:
    - cat
    tty: true
    imagePullPolicy: IfNotPresent
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json