apiVersion: v1
kind: ConfigMap
metadata:
  name: data-configuration
  namespace: default
data:
  database.store: "Data Source=mssqldb;Initial Catalog=Store;User ID=sa;Password=yourStrong(!)Password;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
  database.identity: "Data Source=mssqldb;Initial Catalog=Identity;User ID=sa;Password=yourStrong(!)Password;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
  cloudinarysettings.cloudname: "dhmbxvlld"
  cloudinarysettings.apikey: "762965946552442"
  cloudinarysettings.apisecret: "ePXOkCyUz6Z5dPwZmzWIj_E-zrM"
  tokenkey: "secret token key"
  